##############################################################################
# ha-mail :: /etc/dovecot/dovecot.conf
# Node ${SELF_ROLE} - ${SELF_HOSTNAME}
#
# GENERATED FILE. Edit templates/dovecot/dovecot.conf.tpl instead.
#
# Dovecot is the centre of gravity in this architecture. It owns:
#   * authentication for itself AND for Postfix (SASL over a UNIX socket)
#   * delivery (LMTP) and therefore quota enforcement and Sieve
#   * mailbox replication to ${PEER_HOSTNAME} via dsync
#
# Verify a running configuration with:  doveconf -n
##############################################################################

# Protocols. POP3 is deliberately absent: it has no server-side folder state,
# so a POP3 client that downloads-and-deletes on Node ${SELF_ROLE} produces an
# expunge that dsync must then propagate, and any client that connects to the
# other node mid-sync sees a mailbox that has already been emptied. If you must
# offer POP3, add it here and read docs/AUDIT.md section 4 first.
protocols = imap lmtp sieve

# Listen on every interface. Access is constrained by UFW (public: 143/993
# only) and by per-service `address` settings for the replication listeners,
# which bind to the WireGuard address alone.
listen = *

base_dir = /run/dovecot/
instance_name = dovecot
state_dir = /var/lib/dovecot

# Shown in the IMAP greeting. Naming the node here is worth an enormous amount
# during a failover drill: you can tell at a glance which server a client
# actually reached without reading a single log line.
login_greeting = ${SELF_SHORTNAME} IMAP ready.

# Trusted proxies. Empty on purpose - no proxy sits in front of Dovecot, and a
# populated login_trusted_networks would let a spoofed forwarding header
# rewrite the client IP that fail2ban acts on.
login_trusted_networks =

# Dictionary backends, referenced by name from plugin {} blocks.
dict {
  quota = mysql:/etc/dovecot/dovecot-dict-sql.conf.ext
}

# The order matters: conf.d/*.conf is read lexically, so 95-replication.conf
# sees the final value of mail_plugins set in 10-mail.conf.
!include conf.d/*.conf

# Per-domain TLS certificates for additional hosted domains, generated by
# bin/sni-map.sh. include_try so a fresh node with no extra domains still starts.
!include_try /etc/dovecot/sni.d/*.conf

# Operator escape hatch. Anything here wins over everything above and is never
# overwritten by a redeploy.
!include_try /etc/dovecot/local.conf
