#!/usr/bin/env bash
##############################################################################
# ha-mail :: scripts/55-postfix.sh
##############################################################################

set -Eeuo pipefail
# shellcheck source=../lib/common.sh
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
load_env "${HAMAIL_ENV_FILE:-${HAMAIL_ROOT}/.env}"
require_root

log "configuring Postfix"

ensure_dir /etc/postfix/sql 0750 root:postfix

render "${HAMAIL_TEMPLATES}/postfix/main.cf.tpl"   /etc/postfix/main.cf
render "${HAMAIL_TEMPLATES}/postfix/master.cf.tpl" /etc/postfix/master.cf
render "${HAMAIL_TEMPLATES}/postfix/submission_header_cleanup.tpl" \
       /etc/postfix/submission_header_cleanup
install -m 0644 "${HAMAIL_TEMPLATES}/postfix/header_checks" /etc/postfix/header_checks

for f in "${HAMAIL_TEMPLATES}"/postfix/sql/*.tpl; do
    base="$(basename "${f}" .tpl)"
    render "${f}" "/etc/postfix/sql/${base}" 0640 root:postfix
done
ok "configuration and SQL maps written"

# ---------------------------------------------------------------------------
# Diffie-Hellman parameters
# ---------------------------------------------------------------------------
if [[ ! -f "/etc/postfix/dh${DH_BITS}.pem" ]]; then
    log "generating ${DH_BITS}-bit DH parameters (this takes a few minutes)"
    openssl dhparam -out "/etc/postfix/dh${DH_BITS}.pem" "${DH_BITS}" 2>/dev/null
    chmod 644 "/etc/postfix/dh${DH_BITS}.pem"
    ok "DH parameters generated"
fi

# ---------------------------------------------------------------------------
# System aliases
# ---------------------------------------------------------------------------
# root's mail must go somewhere a human reads. On a mail server, unread root
# mail is how you miss the first sign of a full disk or a failing renewal.
cat > /etc/aliases <<ALIASES
# ha-mail :: /etc/aliases
postmaster:     root
abuse:          root
hostmaster:     root
webmaster:      root
mailer-daemon:  postmaster
nobody:         root
noc:            root
security:       root
root:           ${ADMIN_EMAIL}
ALIASES
newaliases
ok "system aliases set (root -> ${ADMIN_EMAIL})"

# ---------------------------------------------------------------------------
# SNI map (empty until certificates exist; regenerated by 75-certbot.sh)
# ---------------------------------------------------------------------------
: > /etc/postfix/vmail_ssl.map
postmap -F hash:/etc/postfix/vmail_ssl.map

# ---------------------------------------------------------------------------
# Validate before restarting.
# ---------------------------------------------------------------------------
# `postfix check` catches unknown parameters, bad permissions and missing
# files. Restarting a mail server on an unvalidated config is how a typo turns
# into an outage.
if ! postfix check 2>&1 | tee /tmp/postfix-check.out; then
    cat /tmp/postfix-check.out >&2
    die "postfix check failed"
fi
if [[ -s /tmp/postfix-check.out ]]; then
    warn "postfix check produced warnings:"
    cat /tmp/postfix-check.out >&2
fi

# Prove every SQL map can actually be opened and queried. A map with a bad
# password fails at RUNTIME, on live mail, with a temporary reject.
for map in /etc/postfix/sql/*.cf; do
    if ! postmap -q "probe@${DOMAIN}" "mysql:${map}" >/dev/null 2>&1; then
        # An empty result is fine; a connection error is not.
        if postmap -q "probe@${DOMAIN}" "mysql:${map}" 2>&1 | grep -qi 'error\|denied\|refused'; then
            die "map ${map} cannot query the database"
        fi
    fi
done
ok "all SQL maps are readable"

systemctl enable --now postfix
systemctl restart postfix
ok "Postfix running"

postconf -n | head -n 5 >&2
